services:
  php:
    container_name: php_symfony_skeleton
    build:
      context: .
      dockerfile: ./php/Dockerfile
    volumes:
    - ../app:/var/www/html:rw
    - ./:/var/www/html/devops:rw
    ports:
      - 8000:8000
