services:
  php:
    container_name: php_symfony_skeleton
    build:
      context: .
      dockerfile: ./php/Dockerfile
    volumes:
    - ../app:/var/www/html:rw
    - ./:/var/www/html/devops:rw
    ports:
      - 8000:8000

  mariadb:
    container_name: mariadb_symfony_skeleton
    image: mariadb:10.8.3
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
